spring:  
  
    datasource: 
        url: jdbc:mysql://127.0.0.1:3306/my_test?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        
        
    redis:
        database: 0
        host: 127.0.0.1
        port: 6379
        password: 
        timeout: 20000
        pool:
            max-active: 8
            min-idle: 0
            max-idle: 8
            max-wait: -1
    
